# Generated by Django 3.1.5 on 2021-08-25 12:53

from django.db import migrations

#this function retrives the student model object and creates initial data 
def create_data(apps,schema_editor):
    Student = apps.get_model('students','Student')
    Student(name="Andre Vasquez",email="andre@gmail.com", document='22344565',phone='1235432346').save()


class Migration(migrations.Migration):
    #files django will consider using during the migration process
    dependencies = [
        ('students', '0001_initial'),
    ]
    #actions django will perform once the migration is triggered
    operations = [
        migrations.RunPython(create_data),
    ]

#After the data is created run the migrate command in the terminal to create the data defined in the create_data function manage.py migrate
